RaiderEvents = {}

RaiderEvents.eventek = {
  --esx-salary
--esx_drugs
--esx_illegal_drugs
"esx_kekke_tackle:tryTackle",
"cmg3_animations:sync",
"esx_communityservice:sendToCommunityService",
"esx_vangelico_robbery:gioielli",
"lester:vendita",
"esx_illegal_drugs:startHarvestWeed",
"esx_illegal_drugs:startTransformWeed",
"esx_illegal_drugs:startSellWeed",
"esx_illegal_drugs:startHarvestCoke",
"esx_illegal_drugs:startTransformCoke",
"esx_illegal_drugs:startSellCoke",
"esx_illegal_drugs:startHarvestMeth",
"esx_illegal_drugs:startTransformMeth",
"esx_illegal_drugs:startSellMeth",
"esx_illegal_drugs:startHarvestOpium",
"esx_illegal_drugs:startTransformOpium",
"esx_illegal_drugs:startSellOpium",
"esx_illegal_drugs:stopHarvestCoke",
"esx_illegal_drugs:stopTransformCoke",
"esx_illegal_drugs:stopSellCoke",
"esx_illegal_drugs:stopHarvestMeth",
"esx_illegal_drugs:stopTransformMeth",
--esx_bitcoin

"esx_bitcoin:startHarvestKoda",
"esx_bitcoin:startSellKoda",
"esx_bitcoin:stopHarvestKoda",
"esx_bitcoin:stopSellKoda",
--esx_mechanicjob
--esx_vehicleshop
--esx_blanchisseur
"esx_blanchisseur:startWhitening",
"esx_blanchisseur:washMoney",
--outhers
"esx-qalle-hunting:reward",
"esx-qalle-hunting:sell",
"esx_carthief:pay",
"esx_godirtyjob:pay",
"esx_pizza:pay",
"esx_ranger:pay",
"hentailover:xdlol",
"esx_garbagejob:pay",
"esx_truckerjob:pay",
"esx_gopostaljob:pay",
"esx_banksecurity:pay",
"esx_slotmachine:sv:2",
"mellotrainer:adminTempBan",
"mellotrainer:adminKick",
"NB:recruterplayer",
"MF_MobileMeth:RewardPlayers",
"js:jailuser",
"laundry:washcash",
"antilynx8r4a:anticheat",
"antilynxr4:detect",
}